# Generated by Django 5.2.17 on 2026-09-05 22:52

import django.utils.timezone
import osds.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(default=osds.ids.ent_id, editable=False, max_length=40, unique=True)),
                ('status', models.CharField(choices=[('none', 'None'), ('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past due'), ('grace', 'Grace'), ('expired', 'Expired'), ('canceled', 'Canceled'), ('comped', 'Comped')], default='none', max_length=12)),
                ('billing_mode', models.CharField(choices=[('recurring', 'Recurring'), ('term', 'Fixed term'), ('comp', 'Comp'), ('none', 'None')], default='none', max_length=12)),
                ('term_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('dunning_started_at', models.DateTimeField(blank=True, null=True)),
                ('grace_ends_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('comp_reason', models.TextField(blank=True)),
                ('comp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('payment_ref', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'entitlements',
            },
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(default=osds.ids.tier_id, editable=False, max_length=40, unique=True)),
                ('key', models.SlugField()),
                ('name', models.CharField(max_length=100)),
                ('rank', models.PositiveSmallIntegerField()),
                ('purchasable', models.BooleanField(default=False)),
                ('uses_slot', models.BooleanField(default=False)),
                ('price_minor', models.PositiveIntegerField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('perks', models.JSONField(blank=True, default=dict)),
                ('badge_label', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'db_table': 'tiers',
                'ordering': ['rank'],
            },
        ),
    ]
