# Generated by Django 5.2.17 on 2026-09-05 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('directory', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entitlement',
            name='comp_granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comps_granted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entitlement',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='directory.listing'),
        ),
        migrations.AddField(
            model_name='entitlement',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='tier',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='entitlement',
            name='tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entitlements', to='billing.tier'),
        ),
        migrations.AddConstraint(
            model_name='tier',
            constraint=models.UniqueConstraint(fields=('tenant', 'key'), name='uniq_tier_tenant_key'),
        ),
        migrations.AddConstraint(
            model_name='tier',
            constraint=models.UniqueConstraint(fields=('tenant', 'rank'), name='uniq_tier_tenant_rank'),
        ),
        migrations.AddIndex(
            model_name='entitlement',
            index=models.Index(fields=['tenant', 'status'], name='entitlement_tenant__8613e9_idx'),
        ),
        migrations.AddIndex(
            model_name='entitlement',
            index=models.Index(fields=['listing'], name='entitlement_listing_95034b_idx'),
        ),
    ]
