# Generated by Django 5.2.17 on 2026-10-02 19:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
        ('directory', '0012_owner_auth'),
        ('tenants', '0003_smtp_security'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='entitlement',
            name='entitlement_listing_95034b_idx',
        ),
        migrations.AddField(
            model_name='entitlement',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entitlement',
            name='canceled_by',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='entitlement',
            name='dunning_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entitlement',
            name='failed_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entitlement',
            name='hidden_by_expiry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entitlement',
            name='last_failure_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='entitlement',
            name='renewal_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tier',
            name='interval',
            field=models.CharField(blank=True, choices=[('month', 'Monthly'), ('year', 'Yearly')], max_length=5),
        ),
        migrations.AddField(
            model_name='tier',
            name='trial_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='entitlement',
            constraint=models.UniqueConstraint(fields=('listing',), name='uniq_entitlement_listing'),
        ),
        migrations.AddConstraint(
            model_name='tier',
            constraint=models.CheckConstraint(condition=models.Q(('purchasable', True), ('rank', 0), _negated=True), name='tier_rank0_not_purchasable'),
        ),
        migrations.AddConstraint(
            model_name='tier',
            constraint=models.CheckConstraint(condition=models.Q(('purchasable', False), models.Q(('price_minor__gt', 0), models.Q(('currency', ''), _negated=True), models.Q(('interval', ''), _negated=True)), _connector='OR'), name='tier_purchasable_has_price'),
        ),
    ]
