# Generated by Django 5.2.17 on 2026-10-02 20:48

import django.db.models.deletion
import django.utils.timezone
import osds.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_tiers_and_entitlements'),
        ('directory', '0012_owner_auth'),
        ('tenants', '0003_smtp_security'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(default=osds.ids.chk_id, editable=False, max_length=40, unique=True)),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed')], default='started', max_length=10)),
                ('adapter_id', models.CharField(blank=True, max_length=50)),
                ('external_ref', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('expires_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_attempts', to='directory.listing')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout_attempts', to='directory.directoryuser')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_attempts', to='tenants.tenant')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkout_attempts', to='billing.tier')),
            ],
            options={
                'db_table': 'checkout_attempts',
                'indexes': [models.Index(fields=['tenant', 'listing', 'created_at'], name='checkout_at_tenant__df2f81_idx')],
            },
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adapter_id', models.CharField(max_length=50)),
                ('external_event_id', models.CharField(max_length=200)),
                ('kind', models.CharField(max_length=40)),
                ('outcome', models.CharField(choices=[('applied', 'Applied'), ('ignored', 'Ignored')], max_length=10)),
                ('reason', models.CharField(blank=True, max_length=60)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_receipts', to='directory.listing')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_receipts', to='tenants.tenant')),
            ],
            options={
                'db_table': 'payment_receipts',
                'constraints': [models.UniqueConstraint(fields=('tenant', 'adapter_id', 'external_event_id'), name='uniq_payment_receipt_event')],
            },
        ),
    ]
