"""
Django settings for osds project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import unquote, urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Required from the environment; the process does not start without them, the
# same as DATABASE_URL. There is no checked-in fallback for either.

# SECURITY WARNING: keep the secret key secret.
SECRET_KEY = os.environ['DJANGO_SECRET_KEY']

# SECURITY WARNING: never enable in production. Off unless DJANGO_DEBUG is set
# to a truthy value; any DEBUG-only behaviour must stay gated on this.
DEBUG = os.environ.get('DJANGO_DEBUG', '').strip().lower() in {'1', 'true', 'yes', 'on'}

# TenantResolutionMiddleware is the authoritative Host header gate: it runs
# first and returns 404 for any host that is neither the console nor a known
# tenant domain. Django's own ALLOWED_HOSTS check cannot enumerate tenant
# domains, which are added at runtime.
ALLOWED_HOSTS = ['*']

# Deployment topology, from the environment. The console host is where the
# first-run wizard runs and where operators accept invitations; empty means no
# host resolves as the console. The dev slug is consulted only when DEBUG is on
# (see TenantResolutionMiddleware) so a developer without DNS still reaches a
# directory on localhost; it is inert in production.
OSDS_CONSOLE_HOST = os.environ.get('OSDS_CONSOLE_HOST', '')
OSDS_DEV_TENANT_SLUG = os.environ.get('OSDS_DEV_TENANT_SLUG', '')

# Key material for encrypting stored configuration secrets (tenants.secrets),
# separate from SECRET_KEY. Required from the environment so a misconfiguration
# fails at boot rather than at the storage step of the first-run wizard.
OSDS_SECRET_KEY = os.environ['OSDS_SECRET_KEY']

# Marks the session and CSRF cookies Secure. Default true, parsed like
# DJANGO_DEBUG, and deliberately NOT gated on DEBUG: an operator running a
# genuine HTTP-only install needs a way to opt out without also turning DEBUG
# on. Set OSDS_SECURE_COOKIES=false only for such an install.
OSDS_SECURE_COOKIES = os.environ.get(
    'OSDS_SECURE_COOKIES', 'true'
).strip().lower() in {'1', 'true', 'yes', 'on'}

# Listings per page on the public category-browse and search pages.
OSDS_PUBLIC_PAGE_SIZE = 20

# Root of the local-disk media store. Per-tenant subdirectories hang off this,
# resolved at runtime by directory.storage.get_tenant_storage -- never through
# settings.STORAGES, which django-storages reads at import time (decisions.md
# §4). Cloud backends (S3, Azure, GCP) are configured per tenant in the wizard
# and are a later release (#150); only the local backend is wired today.
OSDS_MEDIA_ROOT = os.environ.get('OSDS_MEDIA_ROOT', '').strip() or str(BASE_DIR / 'media')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',  # SearchVectorField, trigram lookups
    'tenants',
    'directory',
    'billing',
    'audit',
]

# Operators are the installation's people; a directory's users are a separate,
# tenant-scoped model (directory.DirectoryUser) and not Django auth users.
AUTH_USER_MODEL = 'tenants.Operator'

MIDDLEWARE = [
    # First: nothing else validates the Host header (ALLOWED_HOSTS=['*']), and
    # SecurityMiddleware's SSL redirect would build a URL from the raw host.
    'osds.middleware.TenantResolutionMiddleware',
    # Above Session/Csrf so its response pass runs after they set their
    # cookies: it strips Secure from those two on first-run wizard responses.
    'osds.middleware.SetupCookieSecurityMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'osds.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'osds.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
#
# Postgres only, taken from DATABASE_URL. No SQLite, no fallback: the app does
# not start without a database URL in the environment. The compose file and the
# CI workflow both provide one.

_db = urlparse(os.environ['DATABASE_URL'])

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': unquote(_db.path).lstrip('/'),
        'USER': unquote(_db.username or ''),
        'PASSWORD': unquote(_db.password or ''),
        'HOST': _db.hostname or '',
        'PORT': str(_db.port or ''),
        # Must stay False. directory.services.upsert_listing raises inside an
        # open transaction (its command-log rows commit independently of the
        # command, spec §11.2), so wrapping requests in a transaction would
        # break every listing write path. This is the default, but set
        # explicitly so flipping it is a deliberate, visible act.
        'ATOMIC_REQUESTS': False,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Sessions and operator login
# ---------------------------------------------------------------------------
# The operator login form is served at /admin/login/ on a tenant's own domain
# and at /login/ on the console host. The two sessions must not carry between
# hosts (decisions.md section 3): clicking a directory in the console opens
# that tenant's /admin and the operator authenticates again there.

# Behind TLS termination the app sees plain http on the wire while the browser
# used https. Without this, CsrfViewMiddleware builds its expected Origin as
# http://<host>, compares it to the browser's https://<host> Origin header,
# and rejects every login POST with a 403. Safe ONLY because the deployment
# proxy strips any client-supplied X-Forwarded-Proto before setting its own --
# otherwise a client could forge it and defeat the SSL redirect. A deployment
# terminating TLS elsewhere must guarantee the same.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Secure flag is env-controlled (OSDS_SECURE_COOKIES, default true), not
# DEBUG-gated -- see the variable's definition above.
SESSION_COOKIE_SECURE = OSDS_SECURE_COOKIES
CSRF_COOKIE_SECURE = OSDS_SECURE_COOKIES

# Host-only cookies: never a parent domain. Tenant domains are arbitrary
# customer domains, generally not subdomains of the console host, so a
# shared-parent cookie is impossible anyway -- pinned here so it stays that
# way and a console session can never be presented at a tenant's /admin.
SESSION_COOKIE_DOMAIN = None
CSRF_COOKIE_DOMAIN = None

# No JavaScript access to the session cookie; Lax keeps it off cross-site
# POSTs while still allowing an operator to follow a link into the admin.
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"

# 12 hours, fixed. No "remember me". The cookie is not rewritten on every
# request (SESSION_SAVE_EVERY_REQUEST stays False), so this is a hard cap on
# an idle admin session, not a sliding window.
SESSION_COOKIE_AGE = 43200
SESSION_SAVE_EVERY_REQUEST = False

# Nothing in OSDS resolves LOGIN_URL today -- directory.access and the console
# views each pass their own reverse()d login URL. It is kept only as the bare
# framework fallback a future @login_required would use; note the value is the
# tenant-admin path and would be wrong on the console host, so any console-side
# login guard must pass its own login_url. LOGIN_REDIRECT_URL and
# LOGOUT_REDIRECT_URL are deliberately unset: every login and logout view names
# its own redirect target.
LOGIN_URL = "/admin/login/"
