"""
Django settings for osds project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import unquote, urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Required from the environment; the process does not start without them, the
# same as DATABASE_URL. There is no checked-in fallback for either.

# SECURITY WARNING: keep the secret key secret.
SECRET_KEY = os.environ['DJANGO_SECRET_KEY']

# SECURITY WARNING: never enable in production. Off unless DJANGO_DEBUG is set
# to a truthy value; any DEBUG-only behaviour must stay gated on this.
DEBUG = os.environ.get('DJANGO_DEBUG', '').strip().lower() in {'1', 'true', 'yes', 'on'}

# TenantResolutionMiddleware is the authoritative Host header gate: it runs
# first and returns 404 for any host that is neither the console nor a known
# tenant domain. Django's own ALLOWED_HOSTS check cannot enumerate tenant
# domains, which are added at runtime.
ALLOWED_HOSTS = ['*']

# Deployment topology, from the environment. The console host is where the
# first-run wizard runs and where operators accept invitations; empty means no
# host resolves as the console. The dev slug is consulted only when DEBUG is on
# (see TenantResolutionMiddleware) so a developer without DNS still reaches a
# directory on localhost; it is inert in production.
OSDS_CONSOLE_HOST = os.environ.get('OSDS_CONSOLE_HOST', '')
OSDS_DEV_TENANT_SLUG = os.environ.get('OSDS_DEV_TENANT_SLUG', '')

# Key material for encrypting stored configuration secrets (tenants.secrets),
# separate from SECRET_KEY. Required from the environment so a misconfiguration
# fails at boot rather than at the storage step of the first-run wizard.
OSDS_SECRET_KEY = os.environ['OSDS_SECRET_KEY']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tenants',
    'directory',
    'billing',
    'audit',
]

# Operators are the installation's people; a directory's users are a separate,
# tenant-scoped model (directory.DirectoryUser) and not Django auth users.
AUTH_USER_MODEL = 'tenants.Operator'

MIDDLEWARE = [
    # First: nothing else validates the Host header (ALLOWED_HOSTS=['*']), and
    # SecurityMiddleware's SSL redirect would build a URL from the raw host.
    'osds.middleware.TenantResolutionMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'osds.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'osds.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
#
# Postgres only, taken from DATABASE_URL. No SQLite, no fallback: the app does
# not start without a database URL in the environment. The compose file and the
# CI workflow both provide one.

_db = urlparse(os.environ['DATABASE_URL'])

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': unquote(_db.path).lstrip('/'),
        'USER': unquote(_db.username or ''),
        'PASSWORD': unquote(_db.password or ''),
        'HOST': _db.hostname or '',
        'PORT': str(_db.port or ''),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
