# Generated by Django 5.2.17 on 2026-09-06 04:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'install_setup',
            },
        ),
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('deployment', 'Deployment'), ('tenant', 'Tenant')], max_length=12)),
                ('key', models.CharField(max_length=100)),
                ('ciphertext', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secrets', to='tenants.tenant')),
            ],
            options={
                'db_table': 'secrets',
                'constraints': [models.UniqueConstraint(condition=models.Q(('tenant__isnull', True)), fields=('key',), name='uniq_secret_deployment_key'), models.UniqueConstraint(condition=models.Q(('tenant__isnull', False)), fields=('tenant', 'key'), name='uniq_secret_tenant_key'), models.CheckConstraint(condition=models.Q(models.Q(('scope', 'deployment'), ('tenant__isnull', True)), models.Q(('scope', 'tenant'), ('tenant__isnull', False)), _connector='OR'), name='secret_scope_matches_tenant')],
            },
        ),
    ]
