# Generated by Django 5.2.17 on 2026-10-05 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_ratelimitcounter'),
        ('tenants', '0003_smtp_security'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatorinvite',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invites', to='tenants.staffmembership'),
        ),
        migrations.AddField(
            model_name='operatorinvite',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operator_invites', to='audit.outboundmessage'),
        ),
    ]
