# Generated by Django 5.2.17 on 2026-09-05 22:52

import django.utils.timezone
import osds.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.JSONField(blank=True, default=dict)),
                ('action', models.CharField(choices=[('viewed', 'Viewed'), ('exported', 'Exported')], max_length=20)),
                ('resource_type', models.CharField(max_length=60)),
                ('resource_id', models.CharField(blank=True, max_length=64)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=400)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('extra', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'access_log',
            },
        ),
        migrations.CreateModel(
            name='CommandLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=60)),
                ('idempotency_key', models.CharField(blank=True, max_length=200, null=True)),
                ('adapter_id', models.CharField(blank=True, max_length=100)),
                ('actor', models.JSONField(blank=True, default=dict)),
                ('trace_id', models.CharField(blank=True, max_length=26)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('outcome', models.CharField(blank=True, choices=[('applied', 'Applied'), ('rejected', 'Rejected'), ('blocked', 'Blocked')], max_length=10, null=True)),
                ('result_event_id', models.CharField(blank=True, max_length=26)),
                ('problem', models.JSONField(blank=True, null=True)),
                ('concluded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'command_log',
            },
        ),
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(default=osds.ids.new_ulid, editable=False, max_length=26, unique=True)),
                ('type', models.CharField(max_length=60)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('subject', models.CharField(max_length=40)),
                ('actor', models.JSONField(blank=True, default=dict)),
                ('origin', models.CharField(blank=True, max_length=100)),
                ('trace_id', models.CharField(blank=True, max_length=26)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('dead', 'Dead-lettered')], default='pending', max_length=10)),
                ('payload_nulled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'outbox_events',
                'ordering': ['id'],
            },
        ),
    ]
