# Generated by Django 5.2.17 on 2026-09-05 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='access_events', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='commandlog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commands', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='outboxevent',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['occurred_at'], name='access_log_occurre_8f5a99_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['resource_type', 'resource_id'], name='access_log_resourc_dec24a_idx'),
        ),
        migrations.AddIndex(
            model_name='commandlog',
            index=models.Index(fields=['idempotency_key'], name='command_log_idempot_c862c5_idx'),
        ),
        migrations.AddIndex(
            model_name='commandlog',
            index=models.Index(fields=['received_at'], name='command_log_receive_3ba289_idx'),
        ),
        migrations.AddIndex(
            model_name='outboxevent',
            index=models.Index(fields=['status', 'id'], name='outbox_even_status_4c8c07_idx'),
        ),
        migrations.AddIndex(
            model_name='outboxevent',
            index=models.Index(fields=['subject'], name='outbox_even_subject_20e128_idx'),
        ),
        migrations.AddIndex(
            model_name='outboxevent',
            index=models.Index(fields=['type'], name='outbox_even_type_b0138b_idx'),
        ),
    ]
