# Generated by Django 5.2.17 on 2026-09-09 01:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_initial'),
        ('tenants', '0002_installsetup_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboxevent',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='outboxevent',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered'), ('dead', 'Dead-lettered')], default='pending', max_length=10),
        ),
        migrations.CreateModel(
            name='OutboxDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=40)),
                ('adapter_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('dead', 'Dead-lettered')], default='pending', max_length=10)),
                ('attempt', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('first_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='audit.outboxevent')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='tenants.tenant')),
            ],
            options={
                'db_table': 'outbox_deliveries',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='outbox_deli_status_493f9c_idx'), models.Index(fields=['adapter_id', 'subject', 'status'], name='outbox_deli_adapter_01d5d5_idx')],
                'constraints': [models.UniqueConstraint(fields=('event', 'adapter_id'), name='uniq_delivery_event_adapter')],
            },
        ),
    ]
