# Generated by Django 5.2.17 on 2026-09-28 01:47

import django.db.models.deletion
import django.utils.timezone
import osds.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_outboxdelivery_and_dispatched'),
        ('tenants', '0002_installsetup_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(default=osds.ids.new_ulid, editable=False, max_length=26, unique=True)),
                ('kind', models.CharField(max_length=60)),
                ('to_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('subject', models.CharField(max_length=200)),
                ('body_text', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('dead', 'Dead-lettered'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('attempt', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('first_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outbound_messages', to='tenants.tenant')),
            ],
            options={
                'db_table': 'outbound_messages',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='outbound_me_status_805da6_idx')],
            },
        ),
    ]
