# Generated by Django 5.2.17 on 2026-10-02 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_outboundmessage'),
        ('tenants', '0003_smtp_security'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimitCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.CharField(max_length=60)),
                ('subject_hash', models.CharField(max_length=64)),
                ('window_start', models.DateTimeField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_limit_counters', to='tenants.tenant')),
            ],
            options={
                'db_table': 'rate_limit_counters',
                'indexes': [models.Index(fields=['window_start'], name='rate_limit__window__6e1c65_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'rule', 'subject_hash', 'window_start'), name='uniq_rate_limit_counter')],
            },
        ),
    ]
