"""Writing an adapter's settings (decisions.md §4.12).

The generic counterpart of ``billing.settings_service`` for an event-subscriber
adapter. Core never names the adapter: it reads the field list, the scopes it
asks for and its optional hooks from the registered subscriber, and writes:

* **Configuration** to ``tenant.settings["adapters"][id]``, through
  ``update_tenant_settings`` so the change is a ``tenant.settings_changed`` event
  -- the audit trail for turning an adapter on or granting it a scope. The values
  are scalars (the validator refuses anything else) and never a secret.
* **Scope grants** as ``scope_pii_contact``/``scope_pii_message`` booleans in the
  same block. Granting is the admin's decision (invariant 8): an adapter asks for
  scopes in its manifest and receives only what is turned on here.
* **Secrets** to the secret store as ``"<id>_<key>"``. A blank secret keeps what
  is stored, an explicit clear removes it, and a refused save leaves nothing behind.
* **Generated secrets.** An adapter that declares ``rotatable_secrets`` (a
  signing key) has any it lacks generated on save, and ``rotate_secret`` replaces
  one. The value is returned once, to be shown once, and is never recoverable.

Hooks the subscriber may provide, all optional: ``validate_settings(values, *,
stored)`` -> list of error strings; ``derive_config(values)`` -> config keys worked
out from the submission (a key set to ``""`` is removed).
"""

from __future__ import annotations

from django.db import transaction

from audit.command_log import log_conclude, log_received, require_autocommit
from osds.adapter_api import SCOPE_LABELS
from osds.adapter_context import adapter_config, provider_id, scope_setting, secret_name
from osds.setting_pattern import pattern_error
from tenants import services as tenant_services
from tenants.models import StaffMembership
from tenants.secrets import delete_secret, has_secret, set_secret


class AdapterSettingsError(ValueError):
    """A submission the settings refuse. Nothing was written."""


class RotateRefused(Exception):
    def __init__(self, reason: str):
        self.reason = reason
        super().__init__(reason)


def settings_fields(subscriber) -> list:
    return list(getattr(subscriber, "settings_fields", lambda: [])())


def secret_field_keys(subscriber) -> "list[str]":
    return [f.key for f in settings_fields(subscriber) if f.secret]


def rotatable(subscriber) -> "tuple[str, ...]":
    return tuple(getattr(subscriber, "rotatable_secrets", ()) or ())


def stored_secrets(tenant, subscriber) -> "set[str]":
    """Keys of this adapter's secrets that have a stored value."""
    adapter_id = provider_id(subscriber)
    return {
        key
        for key in [*secret_field_keys(subscriber), *rotatable(subscriber)]
        if has_secret(secret_name(adapter_id, key), tenant=tenant)
    }


def requested_scopes(subscriber) -> "list[str]":
    return sorted(getattr(subscriber, "scopes", ()) or ())


def scope_labels(subscriber) -> "list[tuple[str, str, str]]":
    """``(scope, form field name, what the admin reads)`` for each scope asked."""
    return [(s, "grant_" + s.replace(":", "_"), SCOPE_LABELS.get(s, s)) for s in requested_scopes(subscriber)]


@transaction.atomic
def update_adapter_settings(
    tenant, *, subscriber, values: dict, grants: dict, clear=frozenset(), changed_by
) -> "dict[str, str]":
    """Apply a submission. ``values`` maps field key -> new value (bool for a
    ``bool`` field, a string otherwise; for a secret field a blank means keep).
    ``grants`` maps scope -> bool for the scopes the adapter asks for. Returns the
    secrets generated by this save, ``{key: value}``, to show once."""
    fields = {f.key: f for f in settings_fields(subscriber)}
    stray = (set(values) | set(clear)) - set(fields)
    if stray:
        raise AdapterSettingsError(f"Unknown setting(s): {', '.join(sorted(stray))}")
    unknown_scopes = set(grants) - set(requested_scopes(subscriber))
    if unknown_scopes:
        raise AdapterSettingsError(f"This adapter does not ask for: {', '.join(sorted(unknown_scopes))}")

    adapter_id = provider_id(subscriber)
    config = adapter_config(tenant, adapter_id, config_key=getattr(subscriber, "config_key", None))
    stored = stored_secrets(tenant, subscriber)

    submitted: dict = {}  # what the validator and derive_config see
    new_secrets: dict = {}
    drop: list = []
    for key, field in fields.items():
        raw = values.get(key)
        if field.secret:
            if key in clear:
                drop.append(key)
                submitted[key] = ""
            elif isinstance(raw, str) and raw.strip():
                new_secrets[key] = raw.strip()
                submitted[key] = raw.strip()
            continue
        if field.kind == "bool":
            submitted[key] = bool(raw)
            config[key] = bool(raw)
        else:
            text = (raw or "").strip() if isinstance(raw, str) else raw
            submitted[key] = text
            if text in (None, ""):
                config.pop(key, None)
            else:
                config[key] = text

    after = (stored | set(new_secrets)) - set(drop)
    validate = getattr(subscriber, "validate_settings", None)
    errors = list(validate(submitted, stored=after | set(rotatable(subscriber)))) if validate else []
    for key, field in fields.items():
        if field.required and field.secret and key not in after:
            errors.append(f"{field.label} is required.")
        # A secret is checked only when typed now; a stored one was checked then.
        typed = new_secrets.get(key) if field.secret else submitted.get(key)
        bad = pattern_error(field, typed)
        if bad:
            errors.append(bad)
    if errors:
        raise AdapterSettingsError(" ".join(errors))

    derive = getattr(subscriber, "derive_config", None)
    if derive:
        for key, value in derive(submitted).items():
            if value in (None, ""):
                config.pop(key, None)
            else:
                config[key] = value
    for scope, granted in grants.items():
        config[scope_setting(scope)] = bool(granted)

    adapters = dict((tenant.settings or {}).get("adapters") or {})
    adapters[adapter_id] = config
    tenant_services.update_tenant_settings(
        tenant=tenant, changes={"adapters": adapters}, changed_by=changed_by
    )
    for key, value in new_secrets.items():
        set_secret(secret_name(adapter_id, key), value, tenant=tenant)
    for key in drop:
        delete_secret(secret_name(adapter_id, key), tenant=tenant)

    generated: dict = {}
    generate = getattr(subscriber, "generate_secret", None)
    if generate:
        for key in rotatable(subscriber):
            if key not in after:
                generated[key] = generate(key)
                set_secret(secret_name(adapter_id, key), generated[key], tenant=tenant)
    return generated


def rotate_secret(tenant, *, subscriber, key: str, operator) -> str:
    """Replace one rotatable secret, at admin. Returns the new value, once. The
    attempt is in the command log; the value is in no log, event or payload."""
    require_autocommit()
    membership = StaffMembership.objects.filter(
        operator=operator, tenant=tenant, status=StaffMembership.Status.ACTIVE
    ).first()
    adapter_id = provider_id(subscriber)
    row = log_received(
        command="adapter.rotate_secret", tenant=tenant, idempotency_key=None,
        actor={
            "type": "admin" if membership and membership.role >= StaffMembership.Role.ADMIN else "staff",
            "id": operator.public_id,
        },
        trace_id=None, origin="", payload={"adapter_id": adapter_id, "key": key},
    )
    try:
        if membership is None or membership.role < StaffMembership.Role.ADMIN:
            raise RotateRefused("forbidden")
        if key not in rotatable(subscriber):
            raise RotateRefused("not_rotatable")
        value = subscriber.generate_secret(key)
        set_secret(secret_name(adapter_id, key), value, tenant=tenant)
    except RotateRefused as exc:
        log_conclude(row, outcome="blocked" if exc.reason == "forbidden" else "rejected",
                     problem={"reason": exc.reason})
        raise
    log_conclude(row, outcome="applied")
    return value
