# Generated by Django 5.2.17 on 2026-09-05 22:52

import django.db.models.deletion
import django.utils.timezone
import osds.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(default=osds.ids.claim_id, editable=False, max_length=40, unique=True)),
                ('status', models.CharField(choices=[('pending_verification', 'Pending verification'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('abandoned', 'Abandoned'), ('disputed', 'Disputed')], default='pending_verification', max_length=24)),
                ('method', models.CharField(choices=[('manual', 'Manual review'), ('phone_otp', 'Phone OTP'), ('domain_email', 'Domain email'), ('gbp_oauth', 'Google Business Profile'), ('postcard', 'Postcard')], max_length=16)),
                ('role_claimed', models.CharField(default='owner', max_length=40)),
                ('verification_started_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('manual_method_used', models.CharField(blank=True, choices=[('phone', 'Phone'), ('email', 'Email'), ('postcard', 'Postcard'), ('website', 'Website'), ('social', 'Social'), ('in_person', 'In person'), ('document', 'Document'), ('other', 'Other')], max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True)),
                ('evidence_ref', models.CharField(blank=True, max_length=500)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('last_step', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'claims',
            },
        ),
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(default=osds.ids.cns_id, editable=False, max_length=40, unique=True)),
                ('channel', models.CharField(max_length=40)),
                ('granted', models.BooleanField()),
                ('granted_at', models.DateTimeField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('text_version', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'db_table': 'consents',
            },
        ),
        migrations.CreateModel(
            name='ConsentText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField()),
                ('version', models.CharField(max_length=20)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'db_table': 'consent_texts',
            },
        ),
        migrations.CreateModel(
            name='DirectoryUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(default=osds.ids.usr_id, editable=False, max_length=40, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('phone_e164', models.CharField(blank=True, max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(default=osds.ids.imp_id, editable=False, max_length=40, unique=True)),
                ('source', models.CharField(default='csv', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('rolled_back', 'Rolled back'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('stored_path', models.CharField(blank=True, max_length=500)),
                ('column_mapping', models.JSONField(blank=True, default=dict)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('suppressed_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('rolled_back_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'db_table': 'import_batches',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(default=osds.ids.lead_id, editable=False, max_length=40, unique=True)),
                ('kind', models.CharField(choices=[('contact_form', 'Contact form'), ('phone_reveal', 'Phone reveal'), ('quote_request', 'Quote request'), ('booking', 'Booking'), ('message', 'Message')], max_length=16)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_e164', models.CharField(blank=True, max_length=16)),
                ('message', models.TextField(blank=True)),
                ('spam_score', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('marked_spam', models.BooleanField(default=False)),
                ('source_page', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('captured', 'Captured'), ('delivered', 'Delivered'), ('delivery_failed', 'Delivery failed')], default='captured', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'db_table': 'leads',
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(default=osds.ids.listing_id, editable=False, max_length=40, unique=True)),
                ('slug', models.SlugField(max_length=200)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('unclaimed', 'Unclaimed'), ('claimed', 'Claimed'), ('suspended', 'Suspended')], default='unclaimed', max_length=12)),
                ('visibility', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('hidden', 'Hidden')], default='draft', max_length=12)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('locality', models.CharField(blank=True, max_length=120)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('geo_precision', models.CharField(choices=[('rooftop', 'Rooftop'), ('street', 'Street'), ('locality', 'Locality'), ('none', 'None')], default='none', max_length=10)),
                ('phone_e164', models.CharField(blank=True, max_length=16)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('social', models.JSONField(blank=True, default=list)),
                ('external_profiles', models.JSONField(blank=True, default=dict)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('custom_fields', models.JSONField(blank=True, default=dict)),
                ('media', models.JSONField(blank=True, default=dict)),
                ('reviews_disabled', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('manual', 'Manual entry'), ('csv_import', 'CSV import'), ('owner_submission', 'Owner submission'), ('api', 'Write API')], default='manual', max_length=20)),
                ('provenance_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'listings',
            },
        ),
        migrations.CreateModel(
            name='ListingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(default=osds.ids.lt_id, editable=False, max_length=40, unique=True)),
                ('key', models.SlugField()),
                ('label_singular', models.CharField(max_length=100)),
                ('label_plural', models.CharField(max_length=100)),
                ('path_segment', models.SlugField()),
                ('claimable', models.BooleanField(default=True)),
                ('fields', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'listing_types',
            },
        ),
        migrations.CreateModel(
            name='SuppressionKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_hash', models.CharField(max_length=64)),
                ('source_listing_public_id', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'db_table': 'suppression_keys',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(default=osds.ids.cat_id, editable=False, max_length=40, unique=True)),
                ('slug', models.SlugField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='directory.category')),
            ],
            options={
                'db_table': 'categories',
                'ordering': ['order', 'name'],
            },
        ),
    ]
