# Generated by Django 5.2.17 on 2026-09-05 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0002_initial'),
        ('directory', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='claim',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='claim',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims_verified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consent',
            name='claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='directory.claim'),
        ),
        migrations.AddField(
            model_name='consent',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='consenttext',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_texts', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='directoryuser',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directory_users', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='claim',
            name='claimant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='directory.directoryuser'),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='rolled_back_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_batches_rolled_back', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='started_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='lead',
            name='spam_marked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_marked_spam', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='consent',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='directory.lead'),
        ),
        migrations.AddField(
            model_name='listing',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='listings', to='directory.category'),
        ),
        migrations.AddField(
            model_name='listing',
            name='current_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='billing.tier'),
        ),
        migrations.AddField(
            model_name='listing',
            name='import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='directory.importbatch'),
        ),
        migrations.AddField(
            model_name='listing',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_listings', to='directory.directoryuser'),
        ),
        migrations.AddField(
            model_name='listing',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_listings', to='directory.directoryuser'),
        ),
        migrations.AddField(
            model_name='listing',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='lead',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='directory.listing'),
        ),
        migrations.AddField(
            model_name='claim',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='directory.listing'),
        ),
        migrations.AddField(
            model_name='listingtype',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_types', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='directory.listingtype'),
        ),
        migrations.AddField(
            model_name='category',
            name='listing_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='directory.listingtype'),
        ),
        migrations.AddField(
            model_name='suppressionkey',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppression_keys', to='tenants.tenant'),
        ),
        migrations.AddConstraint(
            model_name='consenttext',
            constraint=models.UniqueConstraint(fields=('tenant', 'key', 'version'), name='uniq_consenttext_tenant_key_version'),
        ),
        migrations.AddConstraint(
            model_name='directoryuser',
            constraint=models.UniqueConstraint(fields=('tenant', 'email'), name='uniq_user_tenant_email'),
        ),
        migrations.AddConstraint(
            model_name='consent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('claim__isnull', False), ('lead__isnull', True)), models.Q(('claim__isnull', True), ('lead__isnull', False)), _connector='OR'), name='consent_has_exactly_one_subject'),
        ),
        migrations.AddConstraint(
            model_name='listingtype',
            constraint=models.UniqueConstraint(fields=('tenant', 'key'), name='uniq_listingtype_tenant_key'),
        ),
        migrations.AddConstraint(
            model_name='listingtype',
            constraint=models.UniqueConstraint(fields=('tenant', 'path_segment'), name='uniq_listingtype_tenant_path_segment'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['tenant', 'visibility', 'status'], name='listings_tenant__20ff17_idx'),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.UniqueConstraint(fields=('tenant', 'listing_type', 'slug'), name='uniq_listing_tenant_type_slug'),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('geo_precision', 'none'), ('lat__isnull', True), ('lon__isnull', True)), models.Q(models.Q(('geo_precision', 'none'), _negated=True), ('lat__isnull', False), ('lon__isnull', False)), _connector='OR'), name='listing_geo_precision_matches_coordinates'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('tenant', 'listing_type', 'slug'), name='uniq_category_tenant_type_slug'),
        ),
        migrations.AddConstraint(
            model_name='suppressionkey',
            constraint=models.UniqueConstraint(fields=('tenant', 'key_hash'), name='uniq_suppressionkey_tenant_hash'),
        ),
    ]
