# Generated by Django 5.2.17 on 2026-09-06 14:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_initial'),
        ('tenants', '0002_installsetup_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='PathRedirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_prefix', models.CharField(max_length=64)),
                ('new_prefix', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_redirects', to='tenants.tenant')),
            ],
            options={
                'db_table': 'path_redirects',
                'constraints': [models.UniqueConstraint(fields=('tenant', 'old_prefix'), name='uniq_pathredirect_tenant_old_prefix')],
            },
        ),
    ]
