# Generated by Django 5.2.17 on 2026-09-09 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_mediaasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='delimiter',
            field=models.CharField(default=',', max_length=4),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='detected_headers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='encoding',
            field=models.CharField(default='utf-8-sig', max_length=32),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='has_header',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='listing_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='import_batches', to='directory.listingtype'),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='processed_row_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='status',
            field=models.CharField(choices=[('mapping', 'Awaiting column mapping'), ('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('rolled_back', 'Rolled back'), ('failed', 'Failed')], default='mapping', max_length=12),
        ),
    ]
