# Generated by Django 5.2.17 on 2026-09-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0006_importbatch_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='notes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
