# Generated by Django 5.2.17 on 2026-09-30 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0009_claim_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchreindexjob',
            name='cursor',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
