# Generated by Django 5.2.17 on 2026-09-30 20:59

import django.db.models.deletion
import django.utils.timezone
import osds.ids
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_outboundmessage'),
        ('directory', '0010_searchreindexjob_cursor'),
        ('tenants', '0003_smtp_security'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(default=osds.ids.mod_id, editable=False, max_length=40, unique=True)),
                ('item_type', models.CharField(choices=[('claim_dispute', 'Claim dispute'), ('verification_lock', 'Verification lock'), ('claim_block', 'Claim block')], max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('decided', 'Decided')], default='open', max_length=8)),
                ('rules_triggered', models.JSONField(blank=True, default=list)),
                ('priority', models.CharField(default='normal', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision', models.CharField(blank=True, max_length=20)),
                ('rationale', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'moderation_items',
            },
        ),
        migrations.AddField(
            model_name='claim',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims_decided', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='claim',
            name='requested_method',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='claim',
            name='review_reason',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('pending_verification', 'Pending verification'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('abandoned', 'Abandoned'), ('disputed', 'Disputed'), ('superseded', 'Superseded')], default='pending_verification', max_length=24),
        ),
        migrations.AddConstraint(
            model_name='claim',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'approved')), fields=('listing',), name='uniq_one_approved_claim_per_listing'),
        ),
        migrations.AddField(
            model_name='moderationitem',
            name='claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderation_items', to='directory.claim'),
        ),
        migrations.AddField(
            model_name='moderationitem',
            name='claimant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_items', to='directory.directoryuser'),
        ),
        migrations.AddField(
            model_name='moderationitem',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_items_decided', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moderationitem',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_items', to='directory.listing'),
        ),
        migrations.AddField(
            model_name='moderationitem',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_items', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='moderationitem',
            index=models.Index(fields=['tenant', 'status', 'item_type'], name='moderation__tenant__e6f795_idx'),
        ),
        migrations.AddConstraint(
            model_name='moderationitem',
            constraint=models.UniqueConstraint(condition=models.Q(('item_type', 'claim_dispute'), ('status', 'open')), fields=('claim',), name='uniq_open_dispute_item_per_claim'),
        ),
        migrations.AddConstraint(
            model_name='moderationitem',
            constraint=models.UniqueConstraint(condition=models.Q(('item_type__in', ['verification_lock', 'claim_block']), ('status', 'open')), fields=('tenant', 'listing', 'claimant', 'item_type'), name='uniq_open_pair_item_per_type'),
        ),
    ]
