# Generated by Django 5.2.17 on 2026-10-02 15:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0011_claims_review'),
        ('tenants', '0003_smtp_security'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['tenant', 'marked_spam', 'created_at'], name='leads_tenant__1612db_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['listing', 'created_at'], name='leads_listing_51addf_idx'),
        ),
    ]
