# Generated by Django 5.2.17 on 2026-10-02 15:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_ratelimitcounter'),
        ('directory', '0011_claims_review'),
        ('tenants', '0003_smtp_security'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_sessions', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_sessions', to='directory.directoryuser')),
            ],
            options={
                'db_table': 'owner_sessions',
                'indexes': [models.Index(fields=['tenant', 'user'], name='owner_sessi_tenant__ad557b_idx')],
            },
        ),
        migrations.CreateModel(
            name='OwnerSignInToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_signin_tokens', to='audit.outboundmessage')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_signin_tokens', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signin_tokens', to='directory.directoryuser')),
            ],
            options={
                'db_table': 'owner_signin_tokens',
                'indexes': [models.Index(fields=['tenant', 'user', 'created_at'], name='owner_signi_tenant__6fe96b_idx')],
            },
        ),
    ]
